### ISSUE TITLE
RFC: Enhancements and ideas for future

### ISSUE THREAD

**Issue by layershifter** [layershifter/babel-plugin-transform-react-handled-props#6]
# Preamble

I this issue I wan't collect and structure all ideas and enhancements for major release of plugin, make plan for them and implement them step-by-step.

# Options

### properties

I'm thinked about `properties` option to plugin that will allow to define properties for collecting props. 

```json
{
  "plugins": [
    ["transform-react-handled-props", {"properties": ["hiddenProps"]}]
  ]
}
```

**In:**
```jsx
const Example = () => <div />

Example.hiddenProps = ['children']
Example.propTypes = {
  className: propTypes.string
}
```

**Out:**
```jsx
const Example = () => <div />

Example.handledProps = ['children', 'className']
Example.hiddenProps = ['children']
Example.propTypes = {
  className: propTypes.string
}
```

It may be usefull for cases like SUIR's `AutoControlledComponent`.

### resolve

#TODO

----

# Jobs

The plugin performs the following steps to make changes:
* scans for React's import;
* scans for possible React components;
* collects properties;
* adds collected array of `handledProps`.

## Scan for React's import

It's pretty simple step and I think, that we don't need modify it at all. I think we should stick to the theorem that if there is no import, the file doesn't contain anything related to React components.

### To be continued...

**Comment by levithomason** [comment]
### `hiddenProps`

>It may be usefull for cases like SUIR's AutoControlledComponent.

We enforce all auto controlled props to be defined in `propTypes`, see the warnings [here](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/lib/AutoControlledComponent.js#L81).  We also enforce all the auto controlled `default*` prop names are also defined.  In a sense,`autoControlledProps` is more of a pick list for props already defined in `propTypes`.

If the feature is needed elsewhere it may make sense to add.   Just wanted to clarify that SUIR doesn't necessarily need it.

**Comment by layershifter** [comment]
Closing for housekeeping, possible I will back there in future.
