### ISSUE TITLE
Doesn't work with React wrapper methods

### ISSUE THREAD

**Issue by kalbert312** [layershifter/babel-plugin-transform-react-handled-props#62]
Wrapping a function component with `React.forwardRef` or `React.memo` causes it to get ignored.

Example:

```
const Button = React.forwardRef((props, ref) => {
    const rest = // get rest of props not handled
    return (<button ref={ref} {...rest}>{props.label}</button>);
});

Button.propTypes = {
    label: PropTypes.string,
};

export default Button;
```

Can also be chained, e.g `React.memo(React.forwardRef(() => ...))`

**Comment by kalbert312** [comment]
I got around this with

```
const Button = (props, ref) => {
//...
}

const forwarding = React.forwardRef(Button);

Button.propTypes = {
    //...
};

export default forwarding;
```

forwardRef/memo don't support propTypes since a new object with a render method is returned.

**Comment by layershifter** [comment]
Great catch 👍  It's a priority stuff for me, will work on a fix.

**Comment by layershifter** [comment]
Published `babel-plugin-transform-react-handled-props@1.1.0`, please check and provide feedback 🐱

**Comment by kalbert312** [comment]
It works! Thanks.
