### ISSUE TITLE
library concepts not fully defined

### ISSUE THREAD

**Issue by cdaringe** [layershifter/babel-plugin-transform-react-handled-props#9]
# problem statement

- `handledProps` aren't defined formally in the README, and their usage + context are not fully articulated

# discussion

i filed [1601](https://github.com/Semantic-Org/Semantic-UI-React/issues/1601) in hopes to better understand how RSUI wires all of this up.  my understanding has progressed only as far to know that this transform adds a static-ish exports to a component which _can be used_ somehow at runtime to aide in the propagation of props down the component tree.

anyway, this isn't critical or anything, I just thought that I'd share as an _interested user_ that the README didn't get me fully there!

**Comment by layershifter** [comment]
@cdaringe Yes, I need more docs. Thanks for a notice

**Comment by layershifter** [comment]
@cdaringe I've updated README recently, I think now it will be easier understand what the plugin actually does. Sorry, that it took a long time :cry:

**Comment by cdaringe** [comment]
Oh nice!  Thx!
